!EULER METHOD TO SOLVE A DIFFERENTIAL EQUATION
!PROBLEM::SOLVE NUMERICALLY THE DIFFERENTIAL EQUATION dy/dx=1/2(y^3-y/x) using Euler's method at x=1.6,given that y=1 when x=1
!Also find the exact value at x=1.6

PROGRAM EULER_METHOD
 IMPLICIT NONE

 INTEGER::I,J,N,OK
 REAL::F,X0,Y0,H,XF
 REAL,ALLOCATABLE::X(:),Y(:)
PRINT*,"ENTER THE INITIAL VALUE OF X AND Y"
READ*,X0,Y0
PRINT *,X0,Y0

PRINT *,"ENTER THE VALUE OF X  WHERE THE SOLUTION WILL FIND"
 READ*,XF
PRINT*,"ENTER THE VALUE OF H"
 READ*,H
N= (XF-X0)/H
ALLOCATE(X(N+1),Y(N+1),STAT=OK)

X(1)=X0
Y(1)=Y0
IF(OK == 0)THEN
DO I=1,N+1
 X(I+1)=X(I)+H
 Y(I+1)=Y(I)+H*F(X(I),Y(I))
END DO
ELSE
PRINT*,"ALLOCATION FAILURE"
ENDIF

PRINT *,"THE SOLUTION :"
PRINT 10,X(N+1)
10 FORMAT(2X,"X=",F4.1)
PRINT 20,Y(N+1)
20 FORMAT(2X,"Y=",F7.4)

END PROGRAM EULER_METHOD
 



FUNCTION F(X,Y)
 IMPLICIT NONE
 REAL,INTENT(IN)::X,Y
 REAL::F
 F=0.5*(Y**3-Y/X)
END FUNCTION F
